# 该镜像需要依赖的基础镜像
FROM openjdk:8-jdk-alpine
# FROM lhl-docker-java8:1.0
# 将targer目录下的jar包复制到docker容器/home/springboot目录下面目录下面
ADD ./target/crawler-web-1.0.0-SNAPSHOT.jar /root/.jenkins/workspace/data-crawler/crawler-web/target/crawler-web-1.0.0-SNAPSHOT.jar
# 声明服务运行在8080端口
EXPOSE 8101
# 执行命令
CMD ["java","-jar","/home/springboot/crawler-web-1.0.0-SNAPSHOT.jar"]
# 指定维护者名称
MAINTAINER Hide zhoutaoq1029@126.com
